# Generated by Django 4.2.27 on 2026-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fayyaz_Prima_Excel_Automate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='input_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
        migrations.AddField(
            model_name='execution',
            name='output_rows',
            field=models.IntegerField(default=0),
        ),
    ]
